[project]
name = "survival-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lifelines>=0.30.0",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
]
